#CI项目
name: WRT-TEST

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      TARGET:
        default: 'IPQ807X'
        required: true
        type: choice
        options: [IPQ807X, MT7621, X86]
      SOURCE:
        default: 'VIKINGYFY/immortalwrt'
        required: true
        type: choice
        options: [VIKINGYFY/immortalwrt, immortalwrt/immortalwrt, qosmio/openwrt-ipq, LiBwrt/LibWrt, gitdog9527/immortalwrt, gitdog9527/openwrt]
      BRANCH:
        default: 'main'
        required: true
        type: choice
        options: [main, master, 25.12-nss, main-nss]
      CACHES:
        description: '使用上次编译缓存'
        default: 'false'
        required: false
        type: boolean
      CLASHSOURCE:
        default: 'vernesong/OpenClash'
        required: true
        type: choice
        options: [vernesong/OpenClash, gitdog9527/OpenClash]

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{inputs.TARGET}}
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{inputs.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: ImmortalWrt
      #默认WIFI名
      WRT_WIFI: ImmortalWrt
      #默认地址
      WRT_IP: 192.168.31.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{inputs.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{inputs.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{inputs.SOURCE}}
      #使用上次编译缓存
      WRT_CACHES: ${{inputs.CACHES}}
      #openclash源
      CLASHSOURCE: ${{inputs.CLASHSOURCE}}
